title: "VzBoT Documentation"
tagline: Documentation for VzBoT 3D-printers
description: VzBoT Official Documentation
logo: "./assets/images/logo.png"
markdown: kramdown
repository: vethyn/docs
remote_theme: just-the-docs/just-the-docs@v0.4.2
color_scheme: "vzbot"

search_enabled: true
aux_links:
  "GitHub":
    - "https://github.com/VzBoT3D"
  "Ko-Fi":
    - https://ko-fi.com/vez3d
  "Discord":
    - https://discord.gg/KWZWvCMxCq
aux_links_new_tab: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: ./assets/images/rtfm.pngy
